apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
spec:
  acme:
    # Dirección de email usada para registro con Let's Encrypt
    email: tu@email.com

    # Endpoint de ACME (Let's Encrypt)
    server: https://acme-v02.api.letsencrypt.org/directory

    # Secreto donde cert-manager guardará la clave privada de la cuenta ACME
    privateKeySecretRef:
      name: letsencrypt-cloudflare-account-key

    solvers:
      - dns01:
          cloudflare:
            # Email de la cuenta de Cloudflare (puede omitirse si usas solo el token)
            email: tu@email.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
